"""core registry schema

Revision ID: 0002_core_schema
Revises: 0001_extensions
Create Date: 2026-08-26 05:52:46.958636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # autogenerate emits geoalchemy2 types but not this import
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002_core_schema"
down_revision: Union[str, None] = "0001_extensions"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_entry",
        sa.Column("seq", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(length=200), nullable=True),
        sa.Column("actor_role", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=200), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("entry_hash", sa.LargeBinary(length=32), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
    )
    op.create_index("ix_audit_occurred", "audit_entry", ["occurred_at"], unique=False)
    op.create_index("ix_audit_subject", "audit_entry", ["subject_type", "subject_id"], unique=False)
    op.create_table(
        "department",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "watchlist_entry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plate_normalised", sa.String(length=32), nullable=True),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("watchlist_name", sa.String(length=120), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("case_ref", sa.String(length=120), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_watchlist_entry_plate_normalised"),
        "watchlist_entry",
        ["plate_normalised"],
        unique=False,
    )
    op.create_index("ix_watchlist_plate", "watchlist_entry", ["plate_normalised"], unique=False)
    op.create_table(
        "site",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["department_id"], ["department.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("department_id", "name", name="uq_site_dept_name"),
    )
    op.create_index(op.f("ix_site_department_id"), "site", ["department_id"], unique=False)
    op.create_index(op.f("ix_site_district"), "site", ["district"], unique=False)
    op.create_index("ix_site_geom", "site", ["geom"], unique=False, postgresql_using="gist")
    op.create_table(
        "camera",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_ref", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("location_text", sa.Text(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("geom_source", sa.String(length=32), nullable=False),
        sa.Column("confidence_radius_m", sa.Float(), nullable=True),
        sa.Column("resolved_by", sa.String(length=200), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heading_deg", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("ownership_class", sa.String(length=32), nullable=False),
        sa.Column("codec", sa.String(length=32), nullable=True),
        sa.Column("resolution_w", sa.Integer(), nullable=True),
        sa.Column("resolution_h", sa.Integer(), nullable=True),
        sa.Column("declared_fps", sa.Float(), nullable=True),
        sa.Column("measured_fps", sa.Float(), nullable=True),
        sa.Column("transport", sa.String(length=16), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=True),
        sa.Column("archive_mode", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(geom_source = 'unset' AND geom IS NULL) OR (geom_source <> 'unset' AND geom IS NOT NULL)",
            name="ck_camera_geom_matches_source",
        ),
        sa.CheckConstraint(
            "confidence_radius_m IS NULL OR confidence_radius_m > 0",
            name="ck_camera_radius_positive",
        ),
        sa.ForeignKeyConstraint(["department_id"], ["department.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["site_id"], ["site.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_type", "camera_ref", name="uq_camera_source_ref"),
    )
    op.create_index(op.f("ix_camera_camera_ref"), "camera", ["camera_ref"], unique=False)
    op.create_index(op.f("ix_camera_department_id"), "camera", ["department_id"], unique=False)
    op.create_index("ix_camera_dept_status", "camera", ["department_id", "status"], unique=False)
    op.create_index("ix_camera_geom", "camera", ["geom"], unique=False, postgresql_using="gist")
    op.create_index(op.f("ix_camera_site_id"), "camera", ["site_id"], unique=False)
    op.create_index(op.f("ix_camera_status"), "camera", ["status"], unique=False)
    op.create_table(
        "alert",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("watchlist_entry_id", sa.UUID(), nullable=True),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("detection_id", sa.UUID(), nullable=True),
        sa.Column("matched_value", sa.String(length=32), nullable=False),
        sa.Column("match_type", sa.String(length=32), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column("observed_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "raised_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("dedup_window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("disposition", sa.String(length=32), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=200), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["camera_id"], ["camera.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["watchlist_entry_id"], ["watchlist_entry.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_alert_dedup",
        "alert",
        ["camera_id", "matched_value", "dedup_window_start"],
        unique=False,
    )
    op.create_index("ix_alert_state_time", "alert", ["state", "raised_at"], unique=False)
    op.create_table(
        "camera_capability",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("probed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["camera_id"], ["camera.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("camera_id", "name", name="uq_capability_camera_name"),
    )
    op.create_index(
        op.f("ix_camera_capability_camera_id"), "camera_capability", ["camera_id"], unique=False
    )
    op.create_table(
        "detection",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("observed_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("camera_id", sa.UUID(), nullable=False),
        sa.Column("plate_raw", sa.String(length=64), nullable=False),
        sa.Column("plate_normalised", sa.String(length=32), nullable=False),
        sa.Column("corrections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("pts_ms", sa.Float(), nullable=False),
        sa.Column(
            "ingested_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("clock_confidence", sa.Float(), nullable=False),
        sa.Column("crop_path", sa.Text(), nullable=True),
        sa.Column("vehicle_bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_detection_conf"),
        sa.ForeignKeyConstraint(["camera_id"], ["camera.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id", "observed_at_utc"),
    )
    op.create_index(
        "ix_detection_camera_time", "detection", ["camera_id", "observed_at_utc"], unique=False
    )
    op.create_index(
        "ix_detection_plate_time",
        "detection",
        ["plate_normalised", "observed_at_utc"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_detection_plate_time", table_name="detection")
    op.drop_index("ix_detection_camera_time", table_name="detection")
    op.drop_table("detection")
    op.drop_index(op.f("ix_camera_capability_camera_id"), table_name="camera_capability")
    op.drop_table("camera_capability")
    op.drop_index("ix_alert_state_time", table_name="alert")
    op.drop_index("ix_alert_dedup", table_name="alert")
    op.drop_table("alert")
    op.drop_index(op.f("ix_camera_status"), table_name="camera")
    op.drop_index(op.f("ix_camera_site_id"), table_name="camera")
    op.drop_index("ix_camera_geom", table_name="camera", postgresql_using="gist")
    op.drop_index("ix_camera_dept_status", table_name="camera")
    op.drop_index(op.f("ix_camera_department_id"), table_name="camera")
    op.drop_index(op.f("ix_camera_camera_ref"), table_name="camera")
    op.drop_table("camera")
    op.drop_index("ix_site_geom", table_name="site", postgresql_using="gist")
    op.drop_index(op.f("ix_site_district"), table_name="site")
    op.drop_index(op.f("ix_site_department_id"), table_name="site")
    op.drop_table("site")
    op.drop_index("ix_watchlist_plate", table_name="watchlist_entry")
    op.drop_index(op.f("ix_watchlist_entry_plate_normalised"), table_name="watchlist_entry")
    op.drop_table("watchlist_entry")
    op.drop_table("department")
    op.drop_index("ix_audit_subject", table_name="audit_entry")
    op.drop_index("ix_audit_occurred", table_name="audit_entry")
    op.drop_table("audit_entry")
    # ### end Alembic commands ###
