/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoami */
        get: operations["whoami_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/gap-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gap Analysis
         * @description Where this network cannot see, and why.
         */
        get: operations["gap_analysis_cameras_gap_analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cameras
         * @description List cameras within the caller's scope.
         *
         *     `has_geom=false` is how the console finds `coordinate missing` cameras: they are
         *     filtered, never dropped, so an operator can see and fix them.
         */
        get: operations["list_cameras_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera */
        get: operations["get_camera_cameras__camera_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{camera_id}/geom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Camera Geom
         * @description Operator pin-drop. Records manual_survey provenance and an audit entry.
         *
         *     This is what lets a wrong coordinate be corrected in seconds without a redeploy,
         *     and the audit entry is what makes the correction itself evidence.
         */
        patch: operations["patch_camera_geom_cameras__camera_id__geom_patch"];
        trace?: never;
    };
    "/cameras/sync-catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Catalogue
         * @description Diff the gateway catalogue into the registry.
         *
         *     A camera that disappears transitions to UNREACHABLE and is never deleted:
         *     detections reference cameras, and deleting one would orphan evidence. Camera ids
         *     and the camera set can change (§2.1), so the catalogue is the contract and the
         *     URL pattern is not.
         */
        post: operations["sync_catalogue_cameras_sync_catalogue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/bulk-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Import Cameras
         * @description Onboard many cameras from a CSV, row by row.
         *
         *     Model 1 requires bulk onboarding as a platform capability, not only as a script an
         *     engineer runs on the server. This is that capability, and it deliberately shares
         *     its validation with the seed script (`services.registry.camera_import`) so the two
         *     cannot drift into disagreeing about what a valid camera row is.
         *
         *     **Partial success is the normal outcome.** A departmental spreadsheet usually has a
         *     couple of bad rows, and the useful answer is "28 landed, 2 did not, here is why"
         *     rather than a single rejection an operator cannot act on. Good rows are applied;
         *     bad rows are reported with their line number and reason.
         *
         *     **A rejected row is never partially applied.** Validation for a row completes
         *     before anything is written for it, so a row cannot leave a camera half-updated.
         *
         *     Admin-only, and audited before the transaction commits -- the same treatment as
         *     every other mutating endpoint here. Onboarding a camera is an assertion about
         *     where surveillance exists, and it should be attributable.
         */
        post: operations["bulk_import_cameras_cameras_bulk_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{camera_id}/stream-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stream Url
         * @description Playback URL for the console.
         *
         *     The console asks for a camera by id; it never holds an upstream address of its
         *     own. Viewing is audited because watching live video of a public place is an act
         *     that should be attributable.
         */
        get: operations["get_stream_url_cameras__camera_id__stream_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Camera Health
         * @description Per-camera health, including the declared-vs-measured FPS divergence.
         *
         *     The drift column exists because the organiser's integration guide warns that the
         *     reported frame rate cannot be trusted. Showing the gap turns their warning into a
         *     visible platform feature instead of an assumption buried in our pipeline.
         */
        get: operations["camera_health_health_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/gateway": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gateway Status
         * @description Current reachability of the government gateway, from the passive watcher.
         *
         *     Cheap on purpose: this returns the last recorded observation rather than probing,
         *     so the console can poll it without turning a page refresh into load on somebody
         *     else's infrastructure. The watcher does the probing, once a minute.
         */
        get: operations["gateway_status_health_gateway_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Audit Chain
         * @description Recompute the audit hash chain and report any break.
         *
         *     Deliberately available to any authenticated actor, not just admins: the value of
         *     a tamper-evident ledger is that anyone with standing can check it, and restricting
         *     verification to the same role that can alter records defeats the purpose.
         */
        get: operations["verify_audit_chain_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Alerts within the caller's camera scope, highest priority first.
         */
        get: operations["list_alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge Alert */
        post: operations["acknowledge_alert_alerts__alert_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Alert
         * @description Close an alert with a disposition.
         *
         *     The disposition is not bookkeeping: it feeds the per-camera false-positive rate
         *     on the Health screen, which is how the platform measures its own precision
         *     instead of asserting it.
         */
        post: operations["resolve_alert_alerts__alert_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_watchlist_get"];
        put?: never;
        /** Create Watchlist Entry */
        post: operations["create_watchlist_entry_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Watchlist Entry
         * @description Remove a watchlist entry.
         *
         *     Deletion is audited *before* the row goes, and the audit entry carries the plate,
         *     authority and case reference. That ordering is the point: once the row is gone the
         *     ledger is the only remaining evidence that the vehicle was ever watched, and a
         *     surveillance authorisation that can be removed without trace is not an
         *     authorisation.
         *
         *     Entries normally end by expiring -- `valid_to` is mandatory for exactly that
         *     reason. This is for the other cases: a plate entered wrongly, or an authority
         *     withdrawn before its expiry.
         *
         *     Alerts already raised are untouched. They are evidence of what was observed, and
         *     they reference the entry rather than depending on it.
         */
        delete: operations["delete_watchlist_entry_watchlist__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reconstruct Journey
         * @description Reconstruct a vehicle's route across the camera network.
         *
         *     `purpose` is mandatory and written to the audit ledger **before** the query runs,
         *     so a journey query that returns nothing is logged exactly as one that returns a
         *     route. Logging only successful queries would leave the most sensitive case --
         *     someone searching for a plate they should not be -- invisible.
         */
        get: operations["reconstruct_journey_journey_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Journey Pdf
         * @description Signed PDF evidence export for a journey.
         *
         *     Runs the same reconstruction as GET /journey rather than accepting a client-
         *     supplied result: a document signed over whatever the caller posted would attest
         *     to nothing. The export is itself audited, separately from the query, because
         *     producing a distributable evidence document is a more consequential act than
         *     looking at a route on screen.
         */
        get: operations["export_journey_pdf_journey_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/vehicle-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vehicle Counts
         * @description Vehicle counts per time bucket and per camera, over the last `hours`.
         *
         *     This is an independent classifier over the shared detection stream: it opens no
         *     camera and runs no inference of its own. The costly work happened once, in the
         *     ANPR pipeline, and this is what that metadata buys afterwards.
         */
        get: operations["vehicle_counts_analytics_vehicle_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Matched Value */
            matched_value: string;
            /** Match Type */
            match_type: string;
            /** Match Score */
            match_score: number;
            /** Priority */
            priority: number;
            /** State */
            state: string;
            /** Disposition */
            disposition?: string | null;
            /** Observation Count */
            observation_count: number;
            /** Is Movement */
            is_movement: boolean;
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Camera Name */
            camera_name?: string | null;
            /** Camera Source Type */
            camera_source_type?: string | null;
            /** Camera Lat */
            camera_lat?: number | null;
            /** Camera Lon */
            camera_lon?: number | null;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /**
             * Raised At
             * Format: date-time
             */
            raised_at: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Detection Pts Ms */
            detection_pts_ms?: number | null;
            /** Detection Confidence */
            detection_confidence?: number | null;
            /**
             * Corrections
             * @default []
             */
            corrections: Record<string, never>[];
            /** Crop Url */
            crop_url?: string | null;
            /** Watchlist Name */
            watchlist_name?: string | null;
            /** Watchlist Authority */
            watchlist_authority?: string | null;
            /** Watchlist Case Ref */
            watchlist_case_ref?: string | null;
            /** Watchlist Priority */
            watchlist_priority?: number | null;
            /**
             * Corroboration
             * @default {}
             */
            corroboration: Record<string, never>;
            /**
             * Sightings
             * @default []
             */
            sightings: Record<string, never>[];
            /** Acknowledged By */
            acknowledged_by?: string | null;
            /** Acknowledged At */
            acknowledged_at?: string | null;
        };
        /** AuditVerifyOut */
        AuditVerifyOut: {
            /** Valid */
            valid: boolean;
            /** Entries Checked */
            entries_checked: number;
            /** Breaks */
            breaks: Record<string, never>[];
            /** Head Hash */
            head_hash: string | null;
            /** Verified At */
            verified_at: string;
        };
        /** Body_bulk_import_cameras_cameras_bulk_import_post */
        Body_bulk_import_cameras_cameras_bulk_import_post: {
            /**
             * File
             * @description CSV with the camera_geo.csv columns
             */
            file: string;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * BulkImportRejection
         * @description One row that did not land, and why. Line numbers count the header as line 1.
         */
        BulkImportRejection: {
            /** Line */
            line: number;
            /** Camera Ref */
            camera_ref?: string | null;
            /** Reasons */
            reasons: string[];
        };
        /**
         * BulkImportResult
         * @description Outcome of a bulk camera onboarding.
         *
         *     Partial success is the normal case and is reported as such: an operator importing
         *     a departmental spreadsheet wants the good rows in and a list of the ones to fix,
         *     not an all-or-nothing rejection with no indication of which line is wrong.
         */
        BulkImportResult: {
            /** Rows Read */
            rows_read: number;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Unset Coordinates */
            unset_coordinates: number;
            /**
             * Rejections
             * @default []
             */
            rejections: components["schemas"]["BulkImportRejection"][];
            /** Note */
            note?: string | null;
        };
        /** CameraGap */
        CameraGap: {
            /** Camera Id */
            camera_id: string;
            /** Camera Ref */
            camera_ref: string;
            /** Name */
            name: string;
            /** Location Text */
            location_text: string;
            /** District */
            district: string | null;
            /** Kind */
            kind: string;
            /** Detail */
            detail: string;
            /** Confidence Radius M */
            confidence_radius_m: number | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
        };
        /** CameraHealthOut */
        CameraHealthOut: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Camera Ref */
            camera_ref: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Transport */
            transport?: string | null;
            /** Declared Fps */
            declared_fps?: number | null;
            /** Measured Fps */
            measured_fps?: number | null;
            /** Fps Drift Pct */
            fps_drift_pct?: number | null;
            /** Last Seen At */
            last_seen_at?: string | null;
            /**
             * Coordinate Missing
             * @default false
             */
            coordinate_missing: boolean;
        };
        /**
         * CameraOut
         * @description A camera as the console sees it.
         *
         *     `coordinate_missing` is surfaced explicitly rather than left as a null the UI has
         *     to interpret. A camera we cannot place is a fact an operator must see -- it is the
         *     difference between "the vehicle was not there" and "we cannot say".
         */
        CameraOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Camera Ref */
            camera_ref: string;
            /** Name */
            name: string;
            /** Location Text */
            location_text: string;
            /**
             * Department Id
             * Format: uuid
             */
            department_id: string;
            /** Department Code */
            department_code?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Geom Source */
            geom_source: string;
            /** Confidence Radius M */
            confidence_radius_m?: number | null;
            /** Resolved By */
            resolved_by?: string | null;
            /** Resolved At */
            resolved_at?: string | null;
            /**
             * Coordinate Missing
             * @default false
             */
            coordinate_missing: boolean;
            /** Status */
            status: string;
            /** Codec */
            codec?: string | null;
            /** Resolution W */
            resolution_w?: number | null;
            /** Resolution H */
            resolution_h?: number | null;
            /** Declared Fps */
            declared_fps?: number | null;
            /** Measured Fps */
            measured_fps?: number | null;
            /** Transport */
            transport?: string | null;
            /** Source Type */
            source_type: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /**
             * Detection Count
             * @default 0
             */
            detection_count: number;
        };
        /** CoverageGap */
        CoverageGap: {
            /** After Seq */
            after_seq: number;
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Camera Ref */
            camera_ref: string;
            /** Camera Name */
            camera_name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Reason */
            reason: string;
        };
        /** DistrictCoverage */
        DistrictCoverage: {
            /** District */
            district: string;
            /** Cameras Total */
            cameras_total: number;
            /** Cameras Placed */
            cameras_placed: number;
            /** Cameras Unset */
            cameras_unset: number;
            /** Cameras Approximate */
            cameras_approximate: number;
            /** Cameras Degraded */
            cameras_degraded: number;
            /** Cameras Unreachable */
            cameras_unreachable: number;
            /** Mean Confidence Radius M */
            mean_confidence_radius_m: number | null;
            /** Spread Km2 */
            spread_km2: number | null;
            /** Coverage Confidence */
            coverage_confidence: number;
            /** Findings */
            findings: string[];
        };
        /** GapAnalysis */
        GapAnalysis: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Cameras Total */
            cameras_total: number;
            /** Districts */
            districts: components["schemas"]["DistrictCoverage"][];
            /** Camera Gaps */
            camera_gaps: components["schemas"]["CameraGap"][];
            /** Journey Gaps */
            journey_gaps: components["schemas"]["JourneyGap"][];
            /** Summary */
            summary: Record<string, never>;
            /** Interpretation */
            interpretation: string;
        };
        /**
         * GatewayStatusOut
         * @description Whether the government gateway is answering, and since when.
         *
         *     `reachable` is deliberately three-valued. `null` means the watcher has not
         *     completed a check yet -- on a cold start, or on a free-tier host that was asleep --
         *     and the console says "not yet checked" rather than presenting an unknown as an
         *     outage. Reporting a state we have not observed is how a dashboard becomes
         *     something nobody trusts.
         */
        GatewayStatusOut: {
            /** Reachable */
            reachable?: boolean | null;
            /** Last Checked At */
            last_checked_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Unreachable Since */
            unreachable_since?: string | null;
            /** Cameras In Catalogue */
            cameras_in_catalogue?: number | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Consecutive Failures
             * @default 0
             */
            consecutive_failures: number;
            /**
             * Checks Performed
             * @default 0
             */
            checks_performed: number;
            /**
             * Poll Interval S
             * @default 60
             */
            poll_interval_s: number;
        };
        /**
         * GeomPatch
         * @description Operator pin-drop. Writes manual_survey provenance and an audit entry.
         */
        GeomPatch: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Confidence Radius M
             * @default 25
             */
            confidence_radius_m: number;
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JourneyGap
         * @description A camera in scope for real plate queries that recorded nothing.
         */
        JourneyGap: {
            /** Camera Id */
            camera_id: string;
            /** Camera Ref */
            camera_ref: string;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Times Implied */
            times_implied: number;
            /** Detail */
            detail: string;
        };
        /** JourneyHop */
        JourneyHop: {
            /** Seq */
            seq: number;
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Camera Ref */
            camera_ref: string;
            /** Camera Name */
            camera_name: string;
            /** Location Text */
            location_text: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Geom Source */
            geom_source: string;
            /** Confidence Radius M */
            confidence_radius_m: number | null;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /** Pts Ms */
            pts_ms: number;
            /** Clock Confidence */
            clock_confidence: number;
            /** Plate Read */
            plate_read: string;
            /** Evidence Type */
            evidence_type: string;
            /** Corrections */
            corrections: Record<string, never>[];
            /** Confidence */
            confidence: number;
            /** Crop Url */
            crop_url: string | null;
            /**
             * Camera Source Type
             * @default gateway
             */
            camera_source_type: string;
            /** Distance From Prev M */
            distance_from_prev_m?: number | null;
            /** Seconds From Prev */
            seconds_from_prev?: number | null;
            /** Implied Speed Kmph */
            implied_speed_kmph?: number | null;
            /**
             * Within Tolerance Only
             * @default false
             */
            within_tolerance_only: boolean;
        };
        /** JourneyResult */
        JourneyResult: {
            /** Plate */
            plate: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Purpose */
            purpose: string;
            /** Requested By */
            requested_by: string;
            /** Hops */
            hops: components["schemas"]["JourneyHop"][];
            /** Coverage Gaps */
            coverage_gaps: components["schemas"]["CoverageGap"][];
            /** Rejected */
            rejected: components["schemas"]["RejectedHop"][];
            /** Total Distance M */
            total_distance_m: number;
            /** Duration S */
            duration_s: number;
            /** Confidence */
            confidence: number;
            /** Plate Ever Seen */
            plate_ever_seen: boolean;
            /** Query Ms */
            query_ms: number;
            /** Cameras Excluded No Coordinate */
            cameras_excluded_no_coordinate: number;
        };
        /** RejectedHop */
        RejectedHop: {
            /** Camera Ref */
            camera_ref: string;
            /**
             * Observed At Utc
             * Format: date-time
             */
            observed_at_utc: string;
            /** Implied Speed Kmph */
            implied_speed_kmph: number | null;
            /** Reason */
            reason: string;
        };
        /** ResolveRequest */
        ResolveRequest: {
            /**
             * Disposition
             * @description true_positive | false_positive | unable_to_verify
             */
            disposition: string;
            /** Note */
            note?: string | null;
        };
        /**
         * StreamUrlOut
         * @description Playback URL for the console.
         *
         *     The browser never receives an upstream credential: it asks for a camera by id and
         *     the platform returns only what that actor is permitted to play.
         */
        StreamUrlOut: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Camera Ref */
            camera_ref: string;
            /** Transport */
            transport: string;
            /** Url */
            url: string;
            /** Expires In S */
            expires_in_s?: number | null;
        };
        /**
         * SyncResult
         * @description Outcome of a catalogue diff. Counts, plus the ids behind each so it is checkable.
         */
        SyncResult: {
            /** Catalogue Reachable */
            catalogue_reachable: boolean;
            /** Cameras In Catalogue */
            cameras_in_catalogue: number;
            /**
             * Added
             * @default []
             */
            added: string[];
            /**
             * Removed
             * @default []
             */
            removed: string[];
            /**
             * Properties Changed
             * @default []
             */
            properties_changed: string[];
            /**
             * Unchanged
             * @default 0
             */
            unchanged: number;
            /** Note */
            note?: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Role */
            role: string;
            /** Expires In S */
            expires_in_s: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VehicleCountByCamera */
        VehicleCountByCamera: {
            /** Camera Id */
            camera_id: string;
            /** Camera Ref */
            camera_ref: string;
            /** Camera Name */
            camera_name: string;
            /** Reads */
            reads: number;
            /** Distinct Plates */
            distinct_plates: number;
            /** First Seen Utc */
            first_seen_utc: string | null;
            /** Last Seen Utc */
            last_seen_utc: string | null;
        };
        /**
         * VehicleCountResult
         * @description Counts of *identified* vehicles, with the caveat carried in the payload.
         *
         *     `caveat` is part of the response rather than only the documentation because this
         *     number will be read off a screen and quoted. A count of plate reads is a floor on
         *     traffic, not a measure of it, and anything consuming this should have to see that.
         */
        VehicleCountResult: {
            /**
             * Since Utc
             * Format: date-time
             */
            since_utc: string;
            /**
             * Until Utc
             * Format: date-time
             */
            until_utc: string;
            /** Bucket */
            bucket: string;
            /** Total Reads */
            total_reads: number;
            /** Total Distinct Plates */
            total_distinct_plates: number;
            /** Windows */
            windows: components["schemas"]["VehicleCountWindow"][];
            /** By Camera */
            by_camera: components["schemas"]["VehicleCountByCamera"][];
            /** Caveat */
            caveat: string;
        };
        /** VehicleCountWindow */
        VehicleCountWindow: {
            /**
             * Bucket Start Utc
             * Format: date-time
             */
            bucket_start_utc: string;
            /** Reads */
            reads: number;
            /** Distinct Plates */
            distinct_plates: number;
            /** Cameras Reporting */
            cameras_reporting: number;
        };
        /** WatchlistCreate */
        WatchlistCreate: {
            /** Plate Normalised */
            plate_normalised: string;
            /** Watchlist Name */
            watchlist_name: string;
            /** Authority */
            authority: string;
            /** Case Ref */
            case_ref?: string | null;
            /**
             * Priority
             * @default 50
             */
            priority: number;
            /**
             * Severity
             * @default medium
             */
            severity: string;
            /** Colour */
            colour?: string | null;
            /** Make */
            make?: string | null;
            /** Model */
            model?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
        };
        /** WatchlistOut */
        WatchlistOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plate Normalised */
            plate_normalised: string | null;
            /** Watchlist Name */
            watchlist_name: string;
            /** Authority */
            authority: string | null;
            /** Case Ref */
            case_ref: string | null;
            /** Priority */
            priority: number;
            /** Severity */
            severity: string;
            /** Colour */
            colour: string | null;
            /** Make */
            make: string | null;
            /** Model */
            model: string | null;
            /** Active */
            active: boolean;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
            /** Notes */
            notes: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
    gap_analysis_cameras_gap_analysis_get: {
        parameters: {
            query?: {
                journey_window_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GapAnalysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cameras_cameras_get: {
        parameters: {
            query?: {
                /** @description department code */
                department?: string | null;
                status?: string | null;
                has_geom?: boolean | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_cameras__camera_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_camera_geom_cameras__camera_id__geom_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeomPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_catalogue_cameras_sync_catalogue_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
        };
    };
    bulk_import_cameras_cameras_bulk_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_bulk_import_cameras_cameras_bulk_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stream_url_cameras__camera_id__stream_url_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamUrlOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    camera_health_health_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraHealthOut"][];
                };
            };
        };
    };
    gateway_status_health_gateway_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayStatusOut"];
                };
            };
        };
    };
    verify_audit_chain_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyOut"];
                };
            };
        };
    };
    list_alerts_alerts_get: {
        parameters: {
            query?: {
                state?: string | null;
                min_priority?: number | null;
                camera_id?: string | null;
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alert_alerts__alert_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_alert_alerts__alert_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_watchlist_get: {
        parameters: {
            query?: {
                include_expired?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watchlist_entry_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_entry_watchlist__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconstruct_journey_journey_get: {
        parameters: {
            query: {
                plate: string;
                from: string;
                to: string;
                purpose: string;
                /** @description include confusion-explained matches */
                fuzzy?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_journey_pdf_journey_export_get: {
        parameters: {
            query: {
                plate: string;
                from: string;
                to: string;
                purpose: string;
                fuzzy?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vehicle_counts_analytics_vehicle_counts_get: {
        parameters: {
            query?: {
                hours?: number;
                bucket?: string;
                camera_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleCountResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
